/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coloresinfantiless;

import Clase.*;
import classDAO.ClienteDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Clientes extends javax.swing.JPanel {

  Validation v;
  ConectaBD c; 
  Connection co;
  
    public Clientes() {
        initComponents();
        v = new Validation();
        c = new ConectaBD();
        co  = c.getConnection();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        Panel = new javax.swing.JPanel();
        Txt_ID = new javax.swing.JLabel();
        TxtF_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXT_Nom = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        TXT_Ape1 = new javax.swing.JTextField();
        TXT_ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_Tel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBOX_Dir = new javax.swing.JComboBox<>();
        TXT_Dir1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_Dir2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_Dir3 = new javax.swing.JTextField();
        btn_add_cliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TXT_NITemp = new javax.swing.JTextField();
        BuscarCliente = new javax.swing.JButton();
        BuscarCliente1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCliente);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LISTA", jPanel4);

        Txt_ID.setText("ID (Cedula)");

        TxtF_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtF_IDKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel1.setText("Email");

        jLabel3.setText("Apellido");

        jLabel4.setText("Ciudad");

        TXT_Nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NomKeyTyped(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });

        TXT_Ape1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_Ape1KeyTyped(evt);
            }
        });

        TXT_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_ciudadKeyTyped(evt);
            }
        });

        jLabel5.setText("Telefono/Celular");

        TXT_Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_TelActionPerformed(evt);
            }
        });
        TXT_Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_TelKeyTyped(evt);
            }
        });

        jLabel6.setText("Direccion");

        CBOX_Dir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Calle", "Carrera", "Avenida" }));

        TXT_Dir1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_Dir1KeyTyped(evt);
            }
        });

        jLabel7.setText("#");

        TXT_Dir2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_Dir2KeyTyped(evt);
            }
        });

        jLabel8.setText("-");

        TXT_Dir3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_Dir3KeyTyped(evt);
            }
        });

        btn_add_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-documentos.png"))); // NOI18N
        btn_add_cliente.setText("AGREGAR");
        btn_add_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_clienteActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");

        jLabel9.setText("NIT Empresa");

        TXT_NITemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NITempKeyTyped(evt);
            }
        });

        BuscarCliente.setText("Buscar");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });

        BuscarCliente1.setText("Actualizar");
        BuscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Txt_ID)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(34, 34, 34)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXT_Nom)
                                .addComponent(txt_email)
                                .addComponent(TXT_Ape1)
                                .addComponent(TXT_ciudad)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(TxtF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXT_Tel)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(CBOX_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TXT_Dir1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXT_Dir2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TXT_Dir3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TXT_NITemp))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(btn_add_cliente)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarCliente1)))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_ID)
                    .addComponent(TxtF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXT_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXT_Ape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXT_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBOX_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Dir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_Dir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TXT_Dir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXT_NITemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_cliente)
                    .addComponent(BuscarCliente)
                    .addComponent(BuscarCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jTabbedPane1.addTab("INGRESAR CLIENTES", Panel);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Nuestros Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtF_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_IDKeyTyped
     v.validar1(evt.getKeyChar(), evt, TxtF_ID.getText().length());
    }//GEN-LAST:event_TxtF_IDKeyTyped

    private void TXT_NomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_NomKeyTyped
   v.Onlytext(evt.getKeyChar(), evt);
    }//GEN-LAST:event_TXT_NomKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
     
    }//GEN-LAST:event_txt_emailKeyTyped

    private void TXT_Ape1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_Ape1KeyTyped
     v.Onlytext(evt.getKeyChar(), evt);
    }//GEN-LAST:event_TXT_Ape1KeyTyped

    private void TXT_ciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_ciudadKeyTyped
      v.Onlytext(evt.getKeyChar(), evt);
    }//GEN-LAST:event_TXT_ciudadKeyTyped

    private void TXT_TelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_TelKeyTyped
      v.validar1(evt.getKeyChar(), evt, TXT_Tel.getText().length());
    }//GEN-LAST:event_TXT_TelKeyTyped

    private void TXT_Dir1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_Dir1KeyTyped
        v.validar2(evt.getKeyChar(), evt, TXT_Dir1.getText().length());
    }//GEN-LAST:event_TXT_Dir1KeyTyped

    private void TXT_Dir2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_Dir2KeyTyped
       v.validar2(evt.getKeyChar(), evt, TXT_Dir2.getText().length());
    }//GEN-LAST:event_TXT_Dir2KeyTyped

    private void TXT_Dir3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_Dir3KeyTyped
        v.validar2(evt.getKeyChar(), evt, TXT_Dir3.getText().length());
    }//GEN-LAST:event_TXT_Dir3KeyTyped

    private void TXT_NITempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_NITempKeyTyped
        v.validar1(evt.getKeyChar(), evt, TXT_NITemp.getText().length());
    }//GEN-LAST:event_TXT_NITempKeyTyped

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_add_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_clienteActionPerformed
        // TODO add your handling code here:
        try {
        PreparedStatement pst = co.prepareStatement("INSERT INTO clientes(IDclient,nombre,nit,celular,direccion,ciudad,email,apellido) VALUES (?,?,?,?,?,?,?,?)");
        pst.setString(1, TxtF_ID.getText());
        pst.setString(2, TXT_Nom.getText());
        pst.setString(3, TXT_NITemp.getText());
        pst.setString(4, TXT_Tel.getText());
        pst.setString(5, (String) CBOX_Dir.getSelectedItem()+TXT_Dir1.getText()+" # "+TXT_Dir2.getText()+" - "+TXT_Dir3.getText());
        pst.setString(6, TXT_ciudad.getText());
        pst.setString(7, txt_email.getText());
        pst.setString(8, TXT_Ape1.getText());
      
        pst.executeUpdate();
        
        TxtF_ID.setText("");
        TXT_Nom.setText("");
        TXT_NITemp.setText("");
        TXT_Tel.setText("");
        TXT_Dir1.setText("");
        TXT_Dir2.setText("");
        TXT_Dir3.setText("");
        TXT_ciudad.setText("");
        txt_email.setText("");
        TXT_Ape1.setText("");

    } catch (Exception e) {
        System.out.print(e.getMessage());
    }
        
    }//GEN-LAST:event_btn_add_clienteActionPerformed

    private void TXT_TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_TelActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nit");
        modelo.addColumn("Telefono");
        modelo.addColumn("Dirección");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Email");
        

        tablaCliente.setModel(modelo);
        Object[] arrCliente = new Object[8];
        for(classVO.Clientes cliente: ClienteDAO.getListClientes()){
            arrCliente[0] = cliente.getId();
            arrCliente[1] = cliente.getNombre();
            arrCliente[2] = cliente.getEmail();
            arrCliente[3] = cliente.getApellido();
            arrCliente[4] = cliente.getCiudad();
            arrCliente[5] = cliente.getTelefono();
            arrCliente[6] = cliente.getDireccion();
            arrCliente[7] = cliente.getNit();
           
            modelo.addRow(arrCliente);
        }
        tablaCliente.setModel(modelo);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
                                                    
        classVO.Clientes prov = ClienteDAO.buscarProveedores(TxtF_ID.getText());
        System.out.println(prov.getEmail());
        TxtF_ID.setText(prov.getId()+"");
        TXT_Nom.setText(prov.getNombre());
        txt_email.setText(prov.getEmail());
        TXT_Ape1.setText(prov.getApellido());
        TXT_ciudad.setText(prov.getCiudad());
        TXT_Tel.setText(prov.getTelefono());
        TXT_NITemp.setText(prov.getNit());
    }//GEN-LAST:event_BuscarClienteActionPerformed

    private void BuscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCliente1ActionPerformed
        // TODO add your handling code here:                                                    
        classVO.Clientes prov = new classVO.Clientes();
        prov.setId(Integer.parseInt(TxtF_ID.getText()));
        prov.setNombre(TXT_Nom.getText());
        prov.setApellido(TXT_Ape1.getText());
        prov.setEmail(txt_email.getText());
        prov.setCiudad(TXT_ciudad.getText());
        prov.setTelefono(TXT_Tel.getText());
        prov.setDireccion((String) CBOX_Dir.getSelectedItem()+TXT_Dir1.getText()+" # "+TXT_Dir2.getText()+" - "+TXT_Dir3.getText());
        prov.setNit(TXT_NITemp.getText());
        String resp = ClienteDAO.actualizarProveedores(prov);
  
        TXT_Nom.setText("");
        TXT_Ape1.setText("");
        txt_email.setText("");
        TXT_ciudad.setText("");
        TXT_Tel.setText("");
        TXT_NITemp.setText("");
        //cargarProveedores(0);
    
    }//GEN-LAST:event_BuscarCliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCliente;
    private javax.swing.JButton BuscarCliente1;
    private javax.swing.JComboBox<String> CBOX_Dir;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField TXT_Ape1;
    private javax.swing.JTextField TXT_Dir1;
    private javax.swing.JTextField TXT_Dir2;
    private javax.swing.JTextField TXT_Dir3;
    private javax.swing.JTextField TXT_NITemp;
    private javax.swing.JTextField TXT_Nom;
    private javax.swing.JTextField TXT_Tel;
    private javax.swing.JTextField TXT_ciudad;
    private javax.swing.JTextField TxtF_ID;
    private javax.swing.JLabel Txt_ID;
    private javax.swing.JButton btn_add_cliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables

    
}
